# Generated by Django 2.1.5 on 2019-03-19 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_deadline', models.DateTimeField(default=main.models.get_now2)),
                ('todo_title', models.CharField(max_length=200)),
                ('todo_content', models.TextField()),
                ('todo_status', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=3)),
                ('todo_username', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
